### ISSUE TITLE
有些疑问

### ISSUE THREAD

**Issue by liuyike98** [WGrape/lexer#46]
![image](https://user-images.githubusercontent.com/87092276/146672665-4eca1688-4b79-4793-aedc-b3f2533da990.png)
没有学过编译原理，想问一下这种难道不需要做处理吗？字符串里面有诸如\"或者注释符，或者注释符后面出现双引号，这都不需要处理吗？

**Comment by WGrape** [comment]
@liuyike98  感谢提问，图中的这种需要做处理，你理解的是正确的 。

这部分之前版本中没有做处理，目前已在1.8.1版本中支持，具体修改内容可以看 [这个PR](https://github.com/WGrape/lexer/pull/47)

PS ：网站页面有缓存，清除缓存后可以查看最新效果

有问题欢迎提问 ~

<img width="977" alt="img1" src="https://user-images.githubusercontent.com/35942268/146682246-54134e93-05c3-4351-aa7b-07ebb2d5c4e3.png">

**Comment by liuyike98** [comment]
> @liuyike98 感谢提问，图中的这种需要做处理，你理解的是正确的 。
> 
> 这部分之前版本中没有做处理，目前已在1.8.1版本中支持，具体修改内容可以看 [这个PR](https://github.com/WGrape/lexer/pull/47)
> 
> PS ：网站页面有缓存，清除缓存后可以查看最新效果
> 
> 有问题欢迎提问 ~
> 
> <img alt="img1" width="977" src="https://user-images.githubusercontent.com/35942268/146682246-54134e93-05c3-4351-aa7b-07ebb2d5c4e3.png">

感谢回复，谢谢

**Comment by liuyike98** [comment]
@WGrape  
![image](https://user-images.githubusercontent.com/87092276/146767869-91410ff4-8fad-4862-9c64-03c1b3483e9d.png)
我在使用的时候，不知道是我的用法不对还是，有时候会出现\t \r之类的Identifier，我后来把他归入whitespace过滤掉了

**Comment by WGrape** [comment]
@liuyike98 

感谢反馈，这个是正常的，代码中出现的所有字符（空格、制表符、换行符等）都是需要被处理的，如被\t符号识别为```Whitespace```类型，不过可以根据自己的需求，在处理完后做Token的过滤。如下图源码这里会进行Token过滤

<img src="https://user-images.githubusercontent.com/35942268/146862615-ecdc12c3-8a44-49a8-a308-d0130b682494.png" width="500">

另外猜测你使用的是Windows系统，Linux中换行符只有``` \n```，Windows系统中换行符由 ```\r\n``` 两个符号组成，这个```\r``` 符号未定义在```LINEFEED```类型中，所以只能被识别为```Identifier```类型。

看你图中的问题是把 ```如果\r``` 这一个字符串识别成了 ```Identifier``` ，解决这个问题 ，你可以尝试把 ```\r``` 符号加入如下图中的 ```line feed list``` 中。

<img width="399" alt="img" src="https://user-images.githubusercontent.com/35942268/146863281-a5215e96-e3a7-4d75-85c2-ae3def257926.png">

有问题欢迎提问 ~
