### ISSUE TITLE
如果再多一个语法分析就完美了

### ISSUE THREAD

**Issue by xie392** [WGrape/lexer#58]
为什么没有早点遇到这个 demo , 幸苦写了词法分析器，结果一对比，发现自己写得有点捞了……

词法分析出了 tokens ，但生成 AST 树我就有点头疼了，语法分析有没有更为简洁而优雅一点的写法？就像你这个 demo 中的写法，我从没见过这种写法，优雅，确实优雅!!! 如果你能继续写个语法分析就完美了……

这是我自己的语法分析，目前还有很多没处理，像一些循环，选择等的逻辑还识别不出来，现在只能简单的识别一些比较简单的声明
![image](https://user-images.githubusercontent.com/61953437/218302905-195f4b58-1a1f-479e-9dc7-350476b326f1.png)

**Comment by WGrape** [comment]
感谢支持 ！语法分析在正常的开发中，设计也是和这个lexer一样以简单易懂优雅为主要目标，欢迎关注。

**Comment by twitf** [comment]
你好，语法分析有思路吗 想自己动手实践下
